[23092025 16:24:11] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[23092025 16:24:11] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[23092025 16:24:11] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[23092025 16:24:11] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[23092025 16:24:43] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f0bd520d8e0 w 0x5646137ad910 revents 1024
[24092025 17:08:12] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[24092025 17:08:12] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 17:08:12] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 17:08:12] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 17:09:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:10:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:11:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:12:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:13:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:14:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:15:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:16:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:17:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:18:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:19:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:20:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:21:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:22:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:23:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:24:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:25:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[24092025 17:25:47] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f5ef560d8e0 w 0x564094de99f0 revents 1024
[24092025 18:06:23] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[24092025 18:06:23] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 18:06:23] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[24092025 18:06:23] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 18:06:23] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[24092025 18:06:23] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[24092025 18:13:28] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f03fac0d8e0 w 0x56296fd2e7a0 revents 1024
